import { useEffect, useState } from 'react';
import { X, ArrowUp, ArrowDown, Trash, Plus, Check } from '@phosphor-icons/react';
import { contentSchema, type SiteContent } from '../content';
export function Editor({content,onClose,onPreview}:{content:SiteContent;onClose:()=>void;onPreview:(draft:SiteContent)=>void}) {
  const [draft,setDraft]=useState(content);const [tab,setTab]=useState('Splash');const [error,setError]=useState('');const [notice,setNotice]=useState('');
  useEffect(()=>{const previous=document.activeElement as HTMLElement|null;const element=document.querySelector<HTMLDialogElement>('#editor');element?.showModal();return()=>{element?.close();previous?.focus();};},[]);
  function update<K extends keyof SiteContent>(key:K,value:SiteContent[K]) {setDraft(current=>({...current,[key]:value}));setNotice('');}
  function valid() {const result=contentSchema.safeParse(draft);if(!result.success){setError(result.error.issues.map(i=>`${i.path.join('.')}: ${i.message}`).join('\n'));return null;}setError('');return result.data;}
  function save() {const value=valid();if(!value)return;if(value.splashImage.startsWith('blob:')){setError('Image uploads can be previewed, but saving them requires the media backend. Your original file has not been changed.');return;}try{localStorage.setItem('linkhub-draft-v1',JSON.stringify(value));setNotice('Draft saved in this browser. It has not been published.');}catch{setError('This browser could not save the draft. Preview remains available.');}}
  function load() {try{const raw=localStorage.getItem('linkhub-draft-v1');if(!raw){setNotice('No saved draft in this browser yet.');return;}setDraft(contentSchema.parse(JSON.parse(raw)));setNotice('Browser draft restored.');}catch{setError('The saved draft could not be read. Your current edits are still here.');}}
  const field=(key:'tagline'|'intro'|'about'|'rules'|'credits'|'merchUrl',label:string,multiline=false)=><label>{label}{multiline?<textarea rows={8} value={draft[key]} onChange={e=>update(key,e.target.value)}/>:<input value={draft[key]} onChange={e=>update(key,e.target.value)}/>}</label>;
  return <dialog id="editor" onCancel={onClose}><div className="editor"><header><div><span className="small-label">OWNER STUDIO · LOCAL PREVIEW</span><h2>Your corner of the internet.</h2></div><button aria-label="Close editor" onClick={onClose}><X size={24}/></button></header><p className="setup-notice">Owner sign-in and publishing are not connected yet. Edits here are private to this browser; visitors cannot change the live site.</p><nav aria-label="Editor sections">{['Splash','About','Links','Credits','Rules','Merch','Updates'].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>{setTab(t);setError('');}}>{t}</button>)}</nav><div className="editor-fields">
    {tab==='Splash'&&<>{field('tagline','Tagline')}{field('intro','Introduction',true)}<label>Splash artwork · original stays unchanged<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const file=e.target.files?.[0];if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>15*1024*1024){setError('Choose a PNG, JPEG or WebP under 15 MB.');return;}update('splashImage',URL.createObjectURL(file));}}/></label><label>Horizontal image position<input type="range" min="0" max="100" value={draft.imagePosition} onChange={e=>update('imagePosition',Number(e.target.value))}/></label><img className="upload-preview" src={draft.splashImage} alt="Current splash preview"/></>}
    {tab==='About'&&field('about','About Veri',true)}{tab==='Credits'&&field('credits','Credits and attribution',true)}{tab==='Rules'&&field('rules','Stream rules',true)}{tab==='Merch'&&<>{field('merchUrl','Official Fourthwall storefront URL')}<p>The storefront opens directly. An embedded shop will be added only after its compatibility is verified.</p></>}
    {tab==='Links'&&<>{draft.links.map((link,index)=><fieldset key={link.id}><legend>Link {index+1}</legend><label>Label<input value={link.label} onChange={e=>update('links',draft.links.map(l=>l.id===link.id?{...l,label:e.target.value}:l))}/></label><label>URL<input value={link.url} onChange={e=>update('links',draft.links.map(l=>l.id===link.id?{...l,url:e.target.value}:l))}/></label><div className="row"><label className="check"><input type="checkbox" checked={link.hidden} onChange={e=>update('links',draft.links.map(l=>l.id===link.id?{...l,hidden:e.target.checked}:l))}/>Hide link</label><button aria-label="Move link up" disabled={index===0} onClick={()=>{const links=[...draft.links];[links[index-1],links[index]]=[links[index],links[index-1]];update('links',links);}}><ArrowUp/></button><button aria-label="Move link down" disabled={index===draft.links.length-1} onClick={()=>{const links=[...draft.links];[links[index+1],links[index]]=[links[index],links[index+1]];update('links',links);}}><ArrowDown/></button><button aria-label={`Remove ${link.label||'link'}`} onClick={()=>update('links',draft.links.filter(l=>l.id!==link.id))}><Trash/></button></div></fieldset>)}<button onClick={()=>update('links',[...draft.links,{id:crypto.randomUUID(),label:'',url:'',hidden:false}])}><Plus/>Add link</button></>}
    {tab==='Updates'&&<><button onClick={()=>update('updates',[{id:crypto.randomUUID(),title:'',body:'',date:new Date().toLocaleDateString('en-CA'),pinned:false},...draft.updates])}><Plus/>New update</button>{draft.updates.map(post=><fieldset key={post.id}><legend>Update</legend><label>Title<input value={post.title} onChange={e=>update('updates',draft.updates.map(p=>p.id===post.id?{...p,title:e.target.value}:p))}/></label><label>Date<input type="date" value={post.date} onChange={e=>update('updates',draft.updates.map(p=>p.id===post.id?{...p,date:e.target.value}:p))}/></label><label>Message<textarea rows={5} value={post.body} onChange={e=>update('updates',draft.updates.map(p=>p.id===post.id?{...p,body:e.target.value}:p))}/></label><div className="row"><label className="check"><input type="checkbox" checked={post.pinned} onChange={e=>update('updates',draft.updates.map(p=>p.id===post.id?{...p,pinned:e.target.checked}:p))}/>Pin announcement</label><button aria-label="Remove update" onClick={()=>update('updates',draft.updates.filter(p=>p.id!==post.id))}><Trash/></button></div></fieldset>)}</>}
    {error&&<p className="error" role="alert">{error}</p>}{notice&&<p role="status"><Check/>{notice}</p>}</div><footer><button onClick={load}>Restore browser draft</button><button onClick={save}>Save browser draft</button><button className="primary" onClick={()=>{const value=valid();if(value)onPreview(value);}}>Preview</button><button disabled title="Connect owner authentication and content storage first">Publish</button></footer></div></dialog>;
}
